### ISSUE TITLE
Getting "npx scrypted login failed" as HA AddOn

### ISSUE THREAD

**Issue by scottheinrich91** [zone99dev/scrypted-nanit#6]
I was getting "npx scrypted login failed" after installing as an AddOn in HA. I had previously installed this in a docker container of Scrypted, so I knew it could work. After running "npm run scrypted-deploy 127.0.0.1", I'd get: 

```
deploying to 127.0.0.1:10443
TypeError: Cannot read properties of undefined (reading 'username')
    at getLogin (/server/scrypted-nanit-main/node_modules/@scrypted/sdk/bin/index.js:35:25)
    at /server/scrypted-nanit-main/node_modules/@scrypted/sdk/bin/index.js:86:20
    at new Promise (<anonymous>)
    at exports.deploy (/server/scrypted-nanit-main/node_modules/@scrypted/sdk/bin/index.js:57:12)
    at Object.<anonymous> (/server/scrypted-nanit-main/node_modules/@scrypted/sdk/bin/scrypted-deploy.js:16:10)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
Authorization required. Please log in with the following:
     npx scrypted login [ip]
```

but when running that, I get:

```
# npx scrypted login 127.0.0.1
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /server/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/server/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-08-13T21_09_59_099Z-debug-0.log
```

So, I got around this by editing the "scrypted-nanit-main/node_modules/@scrypted/sdk/bin/index.js" file with my hardcoded username and password as follows:

```
    const ret = {
        username: '<USERNAME>',
        password: '<PASSWORD>',
    };
```

This seems to stem from the add-on nature of Scrypted in HA not getting the correct credentials. For now, hard-coding the username/password is fine for my 100% local setup.

**Comment by josephdc18** [comment]
Dumb question probably, but how do I edit the file in Scripted Terminal? I am able to open it with the command "open" but not nano or vim, and once I have opened it I don't seem to be able to edit it. Thanks in advance

**Comment by ijcarson1** [comment]
I'm having a similar issue, where it wasn't letting me authenticate, I hard coded the user values, however I am getting a timeout error 

EDIT: Got it working, had to use the homeassistant.local (no port, no IP etc) for the deploy.
